### ISSUE TITLE
Wrong shortcut key to focus the search bar

### ISSUE THREAD

**Issue by palashjhabak** [frappe/erpnext_documentation#102]
![image](https://user-images.githubusercontent.com/4964924/85919510-3ce6a400-b889-11ea-8489-80d016d1c9eb.png)

Search bar say "?" as the key to focus on it but instead it is "/" on the keyboard. "?" is reached with shift + that key. I understand the key is the same but we tend to press Shift to type "?" so.

**Comment by ankush** [comment]
Closed by https://github.com/frappe/frappe/pull/10723
