### ISSUE TITLE
Avoid using "click here" links

### ISSUE THREAD

**Issue by JohnVeness** [frappe/erpnext_documentation#120]
Currently, there are many links within the documentation labelled "click here". Hopefully it is already understood that these are best avoided. If more info is required, please comment.

**Comment by prasadarr** [comment]
please elaborate, why do you think so?

**Comment by JohnVeness** [comment]
It's been known for over 25 years of web design, but for example https://webaccess.berkeley.edu/ask-pecan/click-here
