### ISSUE TITLE
Separate docs by major release

### ISSUE THREAD

**Issue by barredterra** [frappe/erpnext_documentation#289]
### Problem
At the moment it is very common that docs just reflect the bleeding edge of features. While v13 is being developed, docs get updated with v13 features, old docs from earlier versions get overwritten. For someone using v8 or even v11, the current docs must be completely unusable.

#### a)

For every major release, copy all the docs to a new folder named v12, v13, v14, ... . There they can safely be edited, removed or enhanced. The folder structure could, for example, be `/docs/user/manual/{language}/{major_version}/{module}/*`. Docs that are valid for multiple versions can be copied between versions. The advantage of this approach is that all docs can be viewed on a single site.

#### b)

Have a separate branch for each version, like the code repositories. Deploy each branch to a different subdomain, eg. v12.docs.erpnext.com. Docs that are valid for multiple versions can be backported. The advantage of this approach is that it's very similar to the development workflow.

**Comment by barredterra** [comment]
@prasadarr I'd appreciate your opinion on this topic

**Comment by jalajc** [comment]
@barredterra completely agree. Version part is very important.

However, I see one challenge: Documentation of older versions is incomplete, In case when you need same document update to be pushed multiple versions. e.g. v12 documentation is missing some document, same functionality is v13. While updating documents there is need of judgment to push document update to which version(s).
Also maintain document for each version would require more time and people from community.

**Comment by barredterra** [comment]
Thanks @jalajc , I updated the description to consider your concerns.

**Comment by asbasawaraj** [comment]
@barredterra Yes, we need version-specific documentation.

We have implemented the structure you suggested and are halfway through with v13 screenshots.

We have deployed the changes in a test server here.
https://erpnext-documentation.frappe.cloud/docs/v13/user/manual/en

Each page has a version switched on top right.

**Comment by barredterra** [comment]
Closing this discussion as it is already being worked on. 👍
