### ISSUE TITLE
How to make outgoing calls ?

### ISSUE THREAD

**Issue by nanoharsha** [frappe/erpnext_documentation#87]
Is there any way we have figured out to make outgoing calls from the Erpnext system using the Exotel API ? 
There is a click to call feature in Exotel (https://exotel.com/features/click-to-call/) which we could use to make outgoing calls. 
Ideal behaviour is enabling to allow people to call back the callers as they are going through the issues in the issue doc type, so that it can help gather more details instead of shifting many screens and again copy pasting the number and trying to call.
It also helps link the issues to outgoing calls made for followup.

**Comment by kennethsequeira** [comment]
@nanoharsha check the following: https://github.com/frappe/erpnext/pull/22181

You should raise product related issues[bugs] on the [product](https://github.com/frappe/erpnext/issues) page and any other discussion on the [forum](https://discuss.erpnext.com).
